name: knob_widget
description: A knob widget for flutter
version: 1.0.2
homepage: https://github.com/alr2413/knob_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter_neumorphic: ^3.2.0
  flutter:
    sdk: flutter

  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter: